-- DropForeignKey (idempotent)
ALTER TABLE "GASTOS" DROP CONSTRAINT IF EXISTS "GASTOS_id_proveedor_fkey";

-- AlterTable
ALTER TABLE "GASTOS" DROP COLUMN IF EXISTS "id_proveedor",
ADD COLUMN IF NOT EXISTS "id_instalador_servicio" INTEGER,
ADD COLUMN IF NOT EXISTS "id_proveedor_precio" INTEGER;

-- AlterTable
ALTER TABLE "INSTALADORES" DROP COLUMN IF EXISTS "costo_instalacion",
DROP COLUMN IF EXISTS "nombre_proveedor",
ADD COLUMN IF NOT EXISTS "nombre_instalador" VARCHAR(100) NOT NULL DEFAULT '';

DO $$ BEGIN
  ALTER TABLE "INSTALADORES" ALTER COLUMN "telefono" SET NOT NULL;
EXCEPTION WHEN others THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "INSTALADORES" ALTER COLUMN "correo" SET NOT NULL;
EXCEPTION WHEN others THEN null;
END $$;

-- AlterTable
DO $$ BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'INSTALADORSERVICIOS') THEN
    ALTER TABLE "INSTALADORSERVICIOS" DROP COLUMN IF EXISTS "servicio";
    ALTER TABLE "INSTALADORSERVICIOS" ADD COLUMN IF NOT EXISTS "id_servicio" INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE "INSTALADORSERVICIOS" ADD COLUMN IF NOT EXISTS "notas" VARCHAR(500);
    ALTER TABLE "INSTALADORSERVICIOS" ADD COLUMN IF NOT EXISTS "precio" DECIMAL(10,2) NOT NULL DEFAULT 0;
  END IF;
END $$;

-- AlterTable
ALTER TABLE "PROVEEDORES" DROP COLUMN IF EXISTS "costo";

DO $$ BEGIN
  ALTER TABLE "PROVEEDORES" ALTER COLUMN "telefono" SET NOT NULL;
EXCEPTION WHEN others THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "PROVEEDORES" ALTER COLUMN "correo" SET NOT NULL;
EXCEPTION WHEN others THEN null;
END $$;

-- CreateTable
CREATE TABLE IF NOT EXISTS "PROVEEDORPRECIOS" (
    "id_proveedor_precio" SERIAL NOT NULL,
    "id_proveedor" INTEGER NOT NULL,
    "id_servicio" INTEGER,
    "id_material" INTEGER,
    "precio" DECIMAL(10,2) NOT NULL,
    "notas" VARCHAR(500),

    CONSTRAINT "PROVEEDORPRECIOS_pkey" PRIMARY KEY ("id_proveedor_precio")
);

-- AddForeignKey
DO $$ BEGIN
  ALTER TABLE "PROVEEDORPRECIOS" ADD CONSTRAINT "PROVEEDORPRECIOS_id_proveedor_fkey" FOREIGN KEY ("id_proveedor") REFERENCES "PROVEEDORES"("id_proveedor") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- AddForeignKey
DO $$ BEGIN
  ALTER TABLE "PROVEEDORPRECIOS" ADD CONSTRAINT "PROVEEDORPRECIOS_id_servicio_fkey" FOREIGN KEY ("id_servicio") REFERENCES "SERVICIOS"("id_servicio") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- AddForeignKey
DO $$ BEGIN
  ALTER TABLE "PROVEEDORPRECIOS" ADD CONSTRAINT "PROVEEDORPRECIOS_id_material_fkey" FOREIGN KEY ("id_material") REFERENCES "MATERIALES"("id_material") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'INSTALADORSERVICIOS') THEN
    ALTER TABLE "INSTALADORSERVICIOS" ADD CONSTRAINT "INSTALADORSERVICIOS_id_servicio_fkey" FOREIGN KEY ("id_servicio") REFERENCES "SERVICIOS"("id_servicio") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- AddForeignKey
DO $$ BEGIN
  ALTER TABLE "GASTOS" ADD CONSTRAINT "GASTOS_id_proveedor_precio_fkey" FOREIGN KEY ("id_proveedor_precio") REFERENCES "PROVEEDORPRECIOS"("id_proveedor_precio") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- AddForeignKey (skipped if table doesn't exist)
DO $$ BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'INSTALADORSERVICIOS') THEN
    ALTER TABLE "GASTOS" ADD CONSTRAINT "GASTOS_id_instalador_servicio_fkey" FOREIGN KEY ("id_instalador_servicio") REFERENCES "INSTALADORSERVICIOS"("id_instalador_servicio") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
EXCEPTION WHEN duplicate_object THEN null;
END $$;