-- AlterTable
ALTER TABLE "DETALLEPEDIDO" ADD COLUMN     "id_estatus" INTEGER;

-- AddForeignKey
ALTER TABLE "DETALLEPEDIDO" ADD CONSTRAINT "DETALLEPEDIDO_id_estatus_fkey" FOREIGN KEY ("id_estatus") REFERENCES "ESTATUSPEDIDOS"("id_estatus") ON DELETE SET NULL ON UPDATE CASCADE;
