-- AlterTable
ALTER TABLE "INSTALADORES" ALTER COLUMN "telefono" DROP NOT NULL,
ALTER COLUMN "correo" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PROVEEDORES" ALTER COLUMN "telefono" DROP NOT NULL,
ALTER COLUMN "correo" DROP NOT NULL;
