-- CreateTable
CREATE TABLE "TOKENS_RECUPERACION" (
    "id" SERIAL NOT NULL,
    "id_usuario" INTEGER NOT NULL,
    "token_hash" VARCHAR(64) NOT NULL,
    "expira_en" TIMESTAMP(3) NOT NULL,
    "usado" BOOLEAN NOT NULL DEFAULT false,
    "creado_en" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TOKENS_RECUPERACION_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TOKENS_RECUPERACION_id_usuario_key" ON "TOKENS_RECUPERACION"("id_usuario");

-- CreateIndex
CREATE UNIQUE INDEX "TOKENS_RECUPERACION_token_hash_key" ON "TOKENS_RECUPERACION"("token_hash");

-- AddForeignKey
ALTER TABLE "TOKENS_RECUPERACION" ADD CONSTRAINT "TOKENS_RECUPERACION_id_usuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS"("id_usuario") ON DELETE CASCADE ON UPDATE CASCADE;
