-- CreateTable
CREATE TABLE "COTIZACIONESRECHAZADAS" (
    "id_cotizacion" INTEGER NOT NULL,
    "fecha_rechazo" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "COTIZACIONESRECHAZADAS_pkey" PRIMARY KEY ("id_cotizacion")
);

-- AddForeignKey
ALTER TABLE "COTIZACIONESRECHAZADAS" ADD CONSTRAINT "COTIZACIONESRECHAZADAS_id_cotizacion_fkey" FOREIGN KEY ("id_cotizacion") REFERENCES "COTIZACIONES"("id_cotizacion") ON DELETE CASCADE ON UPDATE CASCADE;
